title = 'Paper'
theme = "paper"
languageCode = 'zh-cn'
baseURL = '/'

[params]
color = 'linen'
github = 'Sricor' 
twitter = 'josricor'

math = true
comments = false
monoDarkIcon = true 
disablePostNavigation = true
