name: hugo

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]
  schedule:
    - cron: "0 15 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Clone Private Repo      # Check out my private repo
        uses: actions/checkout@main
        with:
          ref: main
          repository: ${{ secrets.PRIVATE_REPO }}   # Private repo
          sparse-checkout: public                   # Private repo public content folder
          sparse-checkout-cone-mode: false
          path: content/posts                       # Hugo posts folder
          token: ${{ secrets.ACTION_ACCESS_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify                           # Hugo Build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.ACTION_ACCESS_TOKEN }}
          publish_dir: ./public                       # Hugo static content folder
          publish_branch: gh-pages
          force_orphan: true
